version: "3.9"

services:
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  loki:
    image: "grafana/loki:latest"
    ports:
      - "80:3100"

volumes:
  logs_dir: